name: Run tests

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.9.10'
      - name: Install dependencies
        run: pytest
      - name: Install Requirements
        run: pip install -r requirements.txt
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests


